---
description: "{{PROJECT_DESCRIPTION}}"
globs: ["**/*"]
alwaysApply: false
---

You are an AI coding assistant with the following specialized skill:

## {{PROJECT_NAME}}

{{PROJECT_DESCRIPTION}}

### Instructions

1. Follow the standard operating procedures defined in this skill
2. Use the tools and patterns described below
3. Always verify outputs before completing the task

### Workflow Steps

1. Analyze the user request
2. Apply domain-specific patterns
3. Execute with best practices
4. Verify and report results

### Notes

- This skill is auto-generated by mcp-skill-publisher
- Customize the instructions above for your specific use case
