const chalk = require('chalk');
const ora = require('ora');
const path = require('path');
const fs = require('fs-extra');
const { execSync } = require('child_process');
const { publishMCP } = require('./publish_mcp');
const { publishSkill } = require('./publish_skill');

const TEMPLATES_DIR = path.join(__dirname, '..', 'templates');

function detectProjectType(projectRoot) {
  const types = { mcp: false, skill: false };

  const packageJsonPath = path.join(projectRoot, 'package.json');
  const pyprojectPath = path.join(projectRoot, 'pyproject.toml');
  const setupPyPath = path.join(projectRoot, 'setup.py');

  const hasMCPCode =
    fs.existsSync(packageJsonPath) ||
    fs.existsSync(pyprojectPath) ||
    fs.existsSync(setupPyPath);

  if (hasMCPCode) {
    if (fs.existsSync(packageJsonPath)) {
      const pkg = fs.readJsonSync(packageJsonPath);
      if (pkg.keywords?.some(
        kw => /mcp|model[-\s]?context[-\s]?protocol/i.test(kw)
      )) {
        types.mcp = true;
      }
    }
    if (fs.existsSync(pyprojectPath)) {
      const content = fs.readFileSync(pyprojectPath, 'utf8');
      if (/mcp/i.test(content)) types.mcp = true;
    }
  }

  const skillPaths = [
    path.join(projectRoot, 'skills'),
    path.join(projectRoot, '.cursor', 'rules'),
    path.join(projectRoot, 'rules')
  ];

  for (const sp of skillPaths) {
    if (fs.existsSync(sp)) {
      const files = fs.readdirSync(sp);
      if (files.some(f => f.endsWith('.md') || f.endsWith('.mdc'))) {
        types.skill = true;
        break;
      }
    }
  }

  if (fs.existsSync(path.join(projectRoot, 'smithery.yaml'))) {
    types.mcp = true;
  }

  return types;
}

function bumpVersion(projectRoot) {
  const pkgPath = path.join(projectRoot, 'package.json');
  if (fs.existsSync(pkgPath)) {
    try {
      execSync('npm version patch --no-git-tag-version', {
        cwd: projectRoot,
        stdio: 'pipe'
      });
      const pkg = fs.readJsonSync(pkgPath);
      return pkg.version;
    } catch {
      return require(pkgPath).version;
    }
  }
  return '0.1.0';
}

function ensureConfigFiles(projectRoot, types) {
  const spinner = ora('Checking configuration files...').start();

  const configs = {
    'smithery.yaml': types.mcp,
    'server.json': types.mcp,
    'package.json': types.mcp
  };

  for (const [file, needed] of Object.entries(configs)) {
    const destPath = path.join(projectRoot, file);
    const tplPath = path.join(TEMPLATES_DIR, `${file}.tpl`);

    if (needed && !fs.existsSync(destPath) && fs.existsSync(tplPath)) {
      let tpl = fs.readFileSync(tplPath, 'utf8');

      const pkgName = (() => {
        const pkgPath = path.join(projectRoot, 'package.json');
        if (fs.existsSync(pkgPath)) {
          return fs.readJsonSync(pkgPath).name || path.basename(projectRoot);
        }
        return path.basename(projectRoot);
      })();

      tpl = tpl.replace(/\{\{PROJECT_NAME\}\}/g, pkgName);
      tpl = tpl.replace(/\{\{PROJECT_DESCRIPTION\}\}/g, 'MCP Server generated by mcp-skill-publisher');
      fs.writeFileSync(destPath, tpl);
      spinner.text = `Created ${file}`;
    }
  }

  spinner.succeed('Configuration files checked');
}

async function runPublish(options) {
  const projectRoot = process.cwd();
  const dryRun = options.dryRun || false;
  const forcedScope = options.scope || null;

  console.log(chalk.cyan.bold('\n🚀 mcp-skill-publisher — All-in-One Deploy\n'));
  console.log(chalk.dim(`Project: ${projectRoot}\n`));

  const spinner = ora('Detecting project type...').start();
  const types = forcedScope
    ? { mcp: forcedScope === 'mcp' || forcedScope === 'both', skill: forcedScope === 'skill' || forcedScope === 'both' }
    : detectProjectType(projectRoot);

  const labels = [];
  if (types.mcp) labels.push('MCP Server');
  if (types.skill) labels.push('Agent Skill');
  if (labels.length === 0) labels.push('Unknown');
  spinner.info(`Detected: ${labels.join(' + ')}`);

  ensureConfigFiles(projectRoot, types);

  const version = bumpVersion(projectRoot);
  console.log(chalk.green(`📦 Version: ${version}`));

  if (types.mcp) {
    console.log(chalk.blue('\n📡 === MCP Publish Track ==='));
    await publishMCP(projectRoot, { ...options, version });
  }

  if (types.skill) {
    console.log(chalk.magenta('\n🧠 === Skill Publish Track ==='));
    await publishSkill(projectRoot, { ...options, version });
  }

  printUsage(projectRoot, types);

  if (dryRun) {
    console.log(chalk.yellow('\n⚠  Dry-run mode — nothing was actually published.\n'));
  } else {
    console.log(chalk.green.bold('\n✅ All done! Your project has been published.\n'));
  }
}

function printUsage(projectRoot, types) {
  console.log(chalk.cyan.bold('\n📋 Installation Guide for End Users\n'));
  console.log(chalk.dim('─'.repeat(60)));

  if (types.mcp) {
    const pkgPath = path.join(projectRoot, 'package.json');
    const pkgName = fs.existsSync(pkgPath)
      ? fs.readJsonSync(pkgPath).name
      : path.basename(projectRoot);

    console.log(chalk.yellow('\n🔌 MCP Server — Claude Desktop Config:'));
    console.log(chalk.white(`{
  "mcpServers": {
    "${pkgName}": {
      "command": "npx",
      "args": ["-y", "${pkgName}"]
    }
  }
}`));

    console.log(chalk.yellow('\n🌐 Registry Pages:'));
    console.log(chalk.dim(`  Smithery: https://smithery.ai/server/${pkgName}`));
    console.log(chalk.dim(`  Glama:    https://glama.ai/mcp/servers/${pkgName}`));
    console.log(chalk.dim(`  mcp.so:   https://mcp.so/servers/${pkgName}`));
  }

  if (types.skill) {
    console.log(chalk.yellow('\n🧠 Skill — Cursor Rules Install:'));
    console.log(chalk.white(`  Copy .cursor/rules/*.mdc to your project's .cursor/rules/`));
    console.log(chalk.white(`  Or run: npx mcp-skill-publisher convert -i skill.md -f cursor`));

    console.log(chalk.yellow('\n🧠 Skill — Dify Import:'));
    console.log(chalk.white('  Import dify_workflow.yml via Dify Studio → Import DSL'));
  }

  console.log('');
}

async function runInit(options) {
  const projectRoot = process.cwd();
  const type = options.type || 'hybrid';
  const name = options.name || path.basename(projectRoot);

  console.log(chalk.cyan.bold(`\n🔧 Initializing new project: ${name} (type: ${type})\n`));

  if (type === 'mcp' || type === 'hybrid') {
    const pkgJsonTpl = path.join(TEMPLATES_DIR, 'package.json.tpl');
    if (fs.existsSync(pkgJsonTpl)) {
      let content = fs.readFileSync(pkgJsonTpl, 'utf8');
      content = content.replace(/\{\{PROJECT_NAME\}\}/g, name);
      fs.writeFileSync(path.join(projectRoot, 'package.json'), content);
      console.log(chalk.green('✓ Created package.json'));
    }
  }

  if (type === 'skill' || type === 'hybrid') {
    fs.ensureDirSync(path.join(projectRoot, 'skills'));
    console.log(chalk.green('✓ Created skills/ directory'));
  }

  console.log(chalk.green.bold('\n✅ Project initialized! Run `npx mcp-skill-publisher publish` to deploy.\n'));
}

async function runCheck() {
  const projectRoot = process.cwd();
  const types = detectProjectType(projectRoot);
  let allOk = true;

  console.log(chalk.cyan.bold('\n🔍 Health Check\n'));
  console.log(chalk.dim(`Project: ${projectRoot}\n`));

  if (!types.mcp && !types.skill) {
    console.log(chalk.red('✗ No MCP or Skill project detected.'));
    allOk = false;
  }

  if (types.mcp) {
    console.log(chalk.blue('📡 MCP Checks:'));

    ['package.json', 'smithery.yaml', 'server.json'].forEach(f => {
      const exists = fs.existsSync(path.join(projectRoot, f));
      console.log(`  ${exists ? chalk.green('✓') : chalk.yellow('⚠')} ${f} ${exists ? '' : '(missing — will be auto-generated)'}`);
    });
  }

  if (types.skill) {
    console.log(chalk.magenta('🧠 Skill Checks:'));
    const skillsDir = path.join(projectRoot, 'skills');
    const hasSkills = fs.existsSync(skillsDir) && fs.readdirSync(skillsDir).some(f => f.endsWith('.md'));
    console.log(`  ${hasSkills ? chalk.green('✓') : chalk.red('✗')} skills/ directory with .md files`);
    if (!hasSkills) allOk = false;
  }

  console.log(allOk ? chalk.green.bold('\n✅ All checks passed.\n') : chalk.red.bold('\n✗ Some checks failed.\n'));
}

module.exports = { runPublish, runInit, runCheck, detectProjectType };
